---
name: jack-mechem_nixos-config
project_root: "/home/jack/nixos"
windows:
- vim:
    layout: 5ce1,230x53,0,0,12
    panes:
    - cd /home/jack/nixos
- term:
    layout: 5ce2,230x53,0,0,13
    panes:
    - cd /home/jack/nixos
- nixos-rebuild:
    layout: 5ce3,230x53,0,0,14
    panes:
    - cd /home/jack/nixos
